package cc.vlasenko.site.model;

public enum TextGalleryResource {
    STORY, ASTRAHAN, BALISING, ANDORRA, GREECE, PHUKET, SPAIN, ISTAMBUL, VEYZONA, MINSK, ITALY,
    TENERIFE, FRANCE, PHILIPPINS, AMSTERDAM
}
